categories: "Категорії"
search: "Пошук"
tags: "Тегі"
tagcloud: "Tag Cloud"
tweets: "Tweets"
prev: "Попередня"
next: "Наступна"
comment: "Комментарии"
archive_a: "Пости"
archive_b: "Пости: %s"
page: "Страниця %d"
recent_posts: "Статті і новини"
